trigger:
- main

pool:
  vmImage: pool-ubuntu-2004

steps:
  - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2
    inputs:
      toolMajorVersion: 'V2'