terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.0.0"
    }
  }
}
provider "azurerm" {
  subscription_id = "cee41e09-aa75-4bd5-9863-697325f432d7"
  features {}
}
"id": "/subscriptions/cee41e09-aa75-4bd5-9863-697325f432d7/resourceGroups/poc-environment-rg/providers/Microsoft.Web/sites/POC-Jeff-Bot",
    "name": "POC-Jeff-Bot",
    "type": "Microsoft.Web/sites",
    "kind": "app,linux",
    "location": "West US 2",
    "tags": {
        "ProjectType": "aoai-your-data-service"
    },
    "properties": {
        "name": "POC-Jeff-Bot",
        "state": "Running",
        "hostNames": [
            "poc-jeff-bot.azurewebsites.net"
        ],
        "webSpace": "poc-environment-rg-WestUS2webspace-Linux",
        "selfLink": "https://waws-prod-mwh-105.api.azurewebsites.windows.net:454/subscriptions/cee41e09-aa75-4bd5-9863-697325f432d7/webspaces/poc-environment-rg-WestUS2webspace-Linux/sites/POC-Jeff-Bot",
        "repositorySiteName": "POC-Jeff-Bot",
        "owner": null,
        "usageState": 0,
        "enabled": true,
        "adminEnabled": true,
        "siteScopedCertificatesEnabled": false,
        "afdEnabled": false,
        "enabledHostNames": [
            "poc-jeff-bot.azurewebsites.net",
            "poc-jeff-bot.scm.azurewebsites.net"
        ],
        "siteProperties": {
            "metadata": null,
            "properties": [
                {
                    "name": "LinuxFxVersion",
                    "value": "PYTHON|3.11"
                },
                {
                    "name": "WindowsFxVersion",
                    "value": null
                }
            ],
            "appSettings": null
        },
        "availabilityState": 0,
        "sslCertificates": null,
        "csrs": [],
        "cers": null,
        "siteMode": null,
        "hostNameSslStates": [
            {
                "name": "poc-jeff-bot.azurewebsites.net",
                "sslState": 0,
                "ipBasedSslResult": null,
                "virtualIP": null,
                "virtualIPv6": null,
                "thumbprint": null,
                "certificateResourceId": null,
                "toUpdate": null,
                "toUpdateIpBasedSsl": null,
                "ipBasedSslState": 0,
                "hostType": 0
            },
            {
                "name": "poc-jeff-bot.scm.azurewebsites.net",
                "sslState": 0,
                "ipBasedSslResult": null,
                "virtualIP": null,
                "virtualIPv6": null,
                "thumbprint": null,
                "certificateResourceId": null,
                "toUpdate": null,
                "toUpdateIpBasedSsl": null,
                "ipBasedSslState": 0,
                "hostType": 1
            }
        ],
        "computeMode": null,
        "serverFarm": null,
        "serverFarmId": "/subscriptions/cee41e09-aa75-4bd5-9863-697325f432d7/resourceGroups/poc-environment-rg/providers/Microsoft.Web/serverfarms/asp-POC-Jeff-Bot",
        "reserved": true,
        "isXenon": false,
        "hyperV": false,
        "lastModifiedTimeUtc": "2024-09-26T16:20:17.4666667",
        "storageRecoveryDefaultState": "Running",
        "contentAvailabilityState": 0,
        "runtimeAvailabilityState": 0,
        "dnsConfiguration": {},
        "vnetRouteAllEnabled": false,
        "containerAllocationSubnet": null,
        "useContainerLocalhostBindings": null,
        "vnetImagePullEnabled": false,
        "vnetContentShareEnabled": false,
        "outboundVnetRouting": null,
        "siteConfig": {
            "numberOfWorkers": 1,
            "defaultDocuments": null,
            "netFrameworkVersion": null,
            "phpVersion": null,
            "pythonVersion": null,
            "nodeVersion": null,
            "powerShellVersion": null,
            "linuxFxVersion": "PYTHON|3.11",
            "windowsFxVersion": null,
            "windowsConfiguredStacks": null,
            "requestTracingEnabled": null,
            "remoteDebuggingEnabled": null,
            "remoteDebuggingVersion": null,
            "httpLoggingEnabled": null,
            "azureMonitorLogCategories": null,
            "acrUseManagedIdentityCreds": false,
            "acrUserManagedIdentityID": null,
            "logsDirectorySizeLimit": null,
            "detailedErrorLoggingEnabled": null,
            "publishingUsername": null,
            "publishingPassword": null,
            "appSettings": null,
            "metadata": null,
            "connectionStrings": null,
            "machineKey": null,
            "handlerMappings": null,
            "documentRoot": null,
            "scmType": null,
            "use32BitWorkerProcess": null,
            "webSocketsEnabled": null,
            "alwaysOn": false,
            "javaVersion": null,
            "javaContainer": null,
            "javaContainerVersion": null,
            "appCommandLine": null,
            "managedPipelineMode": null,
            "virtualApplications": null,
            "winAuthAdminState": null,
            "winAuthTenantState": null,
            "customAppPoolIdentityAdminState": null,
            "customAppPoolIdentityTenantState": null,
            "runtimeADUser": null,
            "runtimeADUserPassword": null,
            "loadBalancing": null,
            "routingRules": null,
            "experiments": null,
            "limits": null,
            "autoHealEnabled": null,
            "autoHealRules": null,
            "tracingOptions": null,
            "vnetName": null,
            "vnetRouteAllEnabled": null,
            "vnetPrivatePortsCount": null,
            "publicNetworkAccess": null,
            "cors": null,
            "push": null,
            "apiDefinition": null,
            "apiManagementConfig": null,
            "autoSwapSlotName": null,
            "localMySqlEnabled": null,
            "managedServiceIdentityId": null,
            "xManagedServiceIdentityId": null,
            "keyVaultReferenceIdentity": null,
            "ipSecurityRestrictions": null,
            "ipSecurityRestrictionsDefaultAction": null,
            "scmIpSecurityRestrictions": null,
            "scmIpSecurityRestrictionsDefaultAction": null,
            "scmIpSecurityRestrictionsUseMain": null,
            "http20Enabled": false,
            "minTlsVersion": null,
            "minTlsCipherSuite": null,
            "scmMinTlsCipherSuite": null,
            "supportedTlsCipherSuites": null,
            "scmSupportedTlsCipherSuites": null,
            "scmMinTlsVersion": null,
            "ftpsState": null,
            "preWarmedInstanceCount": null,
            "functionAppScaleLimit": 0,
            "elasticWebAppScaleLimit": null,
            "healthCheckPath": null,
            "fileChangeAuditEnabled": null,
            "functionsRuntimeScaleMonitoringEnabled": null,
            "websiteTimeZone": null,
            "minimumElasticInstanceCount": 0,
            "azureStorageAccounts": null,
            "http20ProxyFlag": null,
            "sitePort": null,
            "antivirusScanEnabled": null,
            "storageType": null,
            "sitePrivateLinkHostEnabled": null,
            "clusteringEnabled": false
        },
        "functionAppConfig": null,
        "daprConfig": null,
        "deploymentId": "POC-Jeff-Bot",
        "slotName": null,
        "trafficManagerHostNames": null,
        "sku": "Free",
        "scmSiteAlsoStopped": false,
        "targetSwapSlot": null,
        "hostingEnvironment": null,
        "hostingEnvironmentProfile": null,
        "clientAffinityEnabled": true,
        "clientAffinityProxyEnabled": false,
        "blockPathTraversal": false,
        "clientCertEnabled": false,
        "clientCertMode": 0,
        "clientCertExclusionPaths": null,
        "hostNamesDisabled": false,
        "ipMode": "IPv4",
        "vnetBackupRestoreEnabled": false,
        "domainVerificationIdentifiers": null,
        "customDomainVerificationId": "11351DB192688446E07F3FFCF542169631C47E81C224CFF23ED09B6906D90D64",
        "kind": "app,linux",
        "managedEnvironmentId": null,
        "workloadProfileName": null,
        "resourceConfig": null,
        "inboundIpAddress": "20.115.232.20",
        "possibleInboundIpAddresses": "20.115.232.20",
        "ftpUsername": "POC-Jeff-Bot\\$POC-Jeff-Bot",
        "ftpsHostName": "ftps://waws-prod-mwh-105.ftp.azurewebsites.windows.net/site/wwwroot",
        "outboundIpAddresses": "51.143.104.5,51.143.108.203,51.143.108.206,40.91.127.143,40.91.127.229,51.143.104.141,20.115.232.20",
        "possibleOutboundIpAddresses": "51.143.104.5,51.143.108.203,51.143.108.206,40.91.127.143,40.91.127.229,51.143.104.141,51.143.110.11,51.143.110.14,51.143.120.200,51.143.122.168,51.143.122.173,51.143.122.175,51.143.104.126,51.143.122.209,51.143.122.250,51.143.123.70,51.143.123.82,51.143.123.85,51.143.124.159,51.143.124.171,51.143.124.230,51.143.126.75,51.143.126.99,51.143.126.194,20.115.232.20",
        "containerSize": 0,
        "dailyMemoryTimeQuota": 0,
        "suspendedTill": null,
        "siteDisabledReason": 0,
        "functionExecutionUnitsCache": null,
        "maxNumberOfWorkers": null,
        "homeStamp": "waws-prod-mwh-105",
        "cloningInfo": null,
        "hostingEnvironmentId": null,
        "tags": {
            "ProjectType": "aoai-your-data-service"
        },
        "resourceGroup": "poc-environment-rg",
        "defaultHostName": "poc-jeff-bot.azurewebsites.net",
        "slotSwapStatus": null,
        "httpsOnly": true,
        "endToEndEncryptionEnabled": false,
        "functionsRuntimeAdminIsolationEnabled": false,
        "redundancyMode": 0,
        "inProgressOperationId": null,
        "geoDistributions": null,
        "privateEndpointConnections": [],
        "publicNetworkAccess": null,
        "buildVersion": null,
        "targetBuildVersion": null,
        "migrationState": null,
        "eligibleLogCategories": "AppServiceAppLogs,AppServiceAuditLogs,AppServiceConsoleLogs,AppServiceHTTPLogs,AppServiceIPSecAuditLogs,AppServicePlatformLogs,ScanLogs,AppServiceAuthenticationLogs",
        "inFlightFeatures": [
            "SiteContainers"
        ],
        "storageAccountRequired": false,
        "virtualNetworkSubnetId": null,
        "keyVaultReferenceIdentity": "SystemAssigned",
        "autoGeneratedDomainNameLabelScope": null,
        "defaultHostNameScope": 0,
        "privateLinkIdentifiers": null,
        "sshEnabled": null
    },
    "identity": {
        "type": "SystemAssigned",
        "tenantId": "ec7f7a18-895e-425d-84e8-e52e65f1162c",
        "principalId": "bf9a7154-613d-4ce5-906d-3e7e978ea492"
    }
}