name: PR Check
on: [pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.25'
      - name: Check out code into the Go module directory
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: make test
        run: |
          make test

  gosec:
    name: gosec
    runs-on: ubuntu-latest
    env:
      GOFLAGS: '-buildvcs=false'
    steps:
      - name: Checkout Source
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Run Gosec Security Scanner
        uses: securego/gosec@223e19b8856e00f02cc67804499a83f77e208f3c # v2.25.0
        with:
          args: './...'

  depscheck:
    name: depscheck
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.25'

      - name: Check out code into the Go module directory
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: make depscheck
        run: |
          make depscheck
